Use latest virtualenv instead of latest pip
Since a latest virtualenv will deploy a latest pip.
Also this will install a new version of setuptools to avoid
"AttributeError: 'EntryPoint' object has no attribute 'resolve'" at ckan
start.